### ISSUE TITLE
Waiting response from Ira, SASS implementation is very necessary! 

### ISSUE THREAD

**Issue by Kronenberg** [Kronenberg/masa-reviewApp#12]
I am provide links to research - 

1. https://github.com/facebookincubator/create-react-app/issues/78
2. https://medium.com/@Connorelsea/using-sass-with-create-react-app-7125d6913760

**Comment by bigcheeseh** [comment]
[Create-react-app with sass](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#post-processing-css)

**Comment by Kronenberg** [comment]
Ye, you're right it is a good source. Just two lines of code!

**Comment by iGlitchime** [comment]
So, it's ready for use. 
Had some troubles with "npm install --save node-sass-chokidar" because it asks me for Xcode install. I suspect it happens only with MacOSX, but how can you solve this problem on Windows or Linux?

**Comment by Kronenberg** [comment]
You're finish your work, but i don't see pull request.

Pull Request example https://github.com/Kronenberg/masa-reviewApp/pull/13 or ask Vlad how to do this.

**Comment by Kronenberg** [comment]
I create pull request from your brunch by myself https://github.com/Kronenberg/masa-reviewApp/pull/14
