### ISSUE TITLE
Move REACT ROUTER CONFIG AND COMPONENTS TO INDEX.jS FROM APP.JS PLEASE! :)

### ISSUE THREAD

**Issue by Kronenberg** [Kronenberg/masa-reviewApp#17]
Vlad u did well, and i am add your code to master
Now u need to move all your logic from App.js to Index.js FILE! :) 

Or better create another router.js file and import just one component to the index.js file 10x! 

p.s. TODA!

**Comment by spone379** [comment]
Done!
