### ISSUE TITLE
Vlad, Ira - Resolve the CONFLICTS on your branches please ! 

### ISSUE THREAD

**Issue by Kronenberg** [Kronenberg/masa-reviewApp#19]
If you have questions ask me!

**Comment by spone379** [comment]
I added the code which I deleted. But I don't understand why I can't delete code?

**Comment by Kronenberg** [comment]
Everything is fine from your side Vlad.

**Comment by Kronenberg** [comment]
Vlad new assignment for you, @spone379 https://github.com/Kronenberg/masa-reviewApp/pull/13
resolve conflict on my branch and push it! :)
GOOD LUCK!
